/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./components/Button.vue')['default']
    Card: typeof import('./components/card/Card.vue')['default']
    CheckRadio: typeof import('./components/form/CheckRadio.vue')['default']
    CheckRadioGroup: typeof import('./components/form/CheckRadioGroup.vue')['default']
    Collapse: typeof import('./components/Collapse.vue')['default']
    CollapseGroup: typeof import('./components/CollapseGroup.vue')['default']
    ContentSlider: typeof import('./components/slider/ContentSlider.vue')['default']
    Default: typeof import('./layouts/default.vue')['default']
    Dropdown: typeof import('./components/Dropdown.vue')['default']
    Field: typeof import('./components/form/Field.vue')['default']
    FieldHelp: typeof import('./components/form/FieldHelp.vue')['default']
    FieldIcon: typeof import('./components/form/FieldIcon.vue')['default']
    FieldLabel: typeof import('./components/form/FieldLabel.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Guest: typeof import('./layouts/guest.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    Heading: typeof import('./components/Heading.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    MdiIcon: typeof import('./components/MdiIcon.vue')['default']
    Modal: typeof import('./components/Modal.vue')['default']
    ModalCard: typeof import('./components/card/ModalCard.vue')['default']
    NavBar: typeof import('./components/NavBar.vue')['default']
    NavBarMenu: typeof import('./components/NavBarMenu.vue')['default']
    NewsLetter: typeof import('./components/NewsLetter.vue')['default']
    OverLayer: typeof import('./components/OverLayer.vue')['default']
    OverviewCard: typeof import('./components/card/OverviewCard.vue')['default']
    Pagination: typeof import('./components/Pagination.vue')['default']
    PillTag: typeof import('./components/PillTag.vue')['default']
    ProductCard: typeof import('./components/card/ProductCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./components/SideBar.vue')['default']
    SidebarDropdown: typeof import('./components/SidebarDropdown.vue')['default']
    SideBarMenuItem: typeof import('./components/SideBarMenuItem.vue')['default']
    Slider: typeof import('./components/slider/Slider.vue')['default']
    Snackbar: typeof import('./components/snackbar/Snackbar.vue')['default']
    SnackbarItem: typeof import('./components/snackbar/SnackbarItem.vue')['default']
    Tab: typeof import('./components/tab/Tab.vue')['default']
    TabGroup: typeof import('./components/tab/TabGroup.vue')['default']
    TabList: typeof import('./components/tab/TabList.vue')['default']
    TabPanel: typeof import('./components/tab/TabPanel.vue')['default']
    TabPanels: typeof import('./components/tab/TabPanels.vue')['default']
    TipTag: typeof import('./components/TipTag.vue')['default']
  }
}
